### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by jonathan-augenstine** [mcci-catena/arduino-lorawan#1]
I was wondering if I could find out the status on this project.  Is it a complete implementation of LoRaWAN or are there missing components?  I would be interested in contributing if additional help is needed.

**Comment by terrillmoore** [comment]
Yes, absolutely – please file issues or send email and I’ll try to respond.   I think issues are better because people can then refer to them, but I’m OK either way.

I went through a support effort with someone else a few weeks ago; it worked out but then he got busy and moved on, and I’ve been busy building hardware and doing day-job things, so haven’t got around to updating. I welcome your involvement. We're about to have a burst of activity anyway, because MCCI is about to receive first units on a shield for the Feather M0 LoRa that adds sensors and NVRAM, which will simplify key management and make it possible to keep the uplink/downlink counts.
