### ISSUE TITLE
Where can i found the <LoraMessage.h> and the <secrets.h> header files?

### ISSUE THREAD

**Issue by martinmmi** [mcci-catena/arduino-lorawan#216]
Thanks

**Comment by matthias-bs** [comment]
You get `LoraMessage.h` by installing the Arduino library `LoRa_Serialization`. You have to create `secrets.h` by yourself - just rename `examples/arduino_lorawan_esp32_example/secrets.h.template` to `secrets.h` and fill in the same values as in the LoRaWAN network provider's settings. In most cases you get the DevEUI with your LoRaWAN radio module, otherwise you can generate it in the LoRaWAN network provider's console (same as with the AppKey).

**Comment by martinmmi** [comment]
Hello Matthias! Thanks for your fast reply. 

I founded the LoraMessage.h part and I defined my ttgo_lora32_v21 board. Also i founded th secrets.h file in this git repo. I think, everything is fine with this files. 

But i get some much more errors with the default `examples/arduino_lorawan_esp32_example/secrets.h.template` example. I will open a new issue for this
